# Generated by Django 4.2.6 on 2023-11-06 01:40

import desingapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desingapp', '0004_alter_application_photo_file_delete_fotoform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo_file',
            field=models.ImageField(max_length=254, upload_to='images/', validators=[desingapp.models.Application.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=254, verbose_name='Статус'),
        ),
    ]
