# Generated by Django 4.2.6 on 2023-11-06 02:21

import desingapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desingapp', '0005_alter_application_photo_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo_file',
            field=models.ImageField(max_length=254, upload_to='media/', validators=[desingapp.models.Application.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])]),
        ),
    ]
